name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

env:
  WORKING_DIR: './icedata-v2/'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run chmod to make gradlew executable
        working-directory: ${{ env.WORKING_DIR }}
        run: chmod +x ./gradlew

      - name: Build with Gradle
        working-directory: ${{ env.WORKING_DIR }}
        run: ./gradlew clean test
